# Use the official Node.js 14 image as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) files
COPY ./package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the server's source code
COPY ./ .

# Build the project if necessary
# If the server does not need to be built, remove this line
RUN npm run build

# Expose the port the server listens on
EXPOSE 3020

# Run the server
CMD [ "npm", "run", "start" ]